config/routes.rb
HipService::Application.routes.draw do
   devise_for :users, controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
    }
  root 'tasks#index'

  resources :tasks do
    collection do
      get :load
    end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
	validates :description, :end_date, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :tasks, dependent: :destroy

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.save!
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
  before_filter :authenticate_user!

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_filter :authenticate_user!
	def facebook
  	@user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
    	flash.notice = "Добро пожаловать"
      sign_in_and_redirect @user
    else
      session["devise.facebook_data"] = @user.attributes
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	expose (:tasks) {
    current_user.tasks
  }
  expose :task, attributes: :task_params

  def index
  end

  def new
  end

  def create
    date_end = Date.strptime(params[:task][:end_date], '%m/%d/%Y') if params[:task][:end_date].present?
    @task = Task.create(task_params.merge!(end_date: date_end))
    flash[:error] = @task.errors.full_messages if @task.errors.present?
  end

  def update
  	task.update(task_params)
  end

  private
    def task_params
      params.require(:task).permit(:user_id, :description, :end_date, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
    case level
      when :notice then "info"
      when :error then "danger"
      when :alert then "warning"
    end
  end
end

app/views/home/index.html.slim
h1 home index

app/views/layout_components/_flash_messages.html.slim
- [:notice, :error, :alert].each do |level|
  - unless flash[level].blank?
    div class="alert alert-#{flash_class(level)}"
      a.close href="#"
      = content_tag :p, flash[level]

app/views/layout_components/_header.html.slim
.header.bottom20
  ul.nav.nav-pills.pull-right
    li.active
      = link_to 'Home', root_url
    - if user_signed_in?
      li.dropdown
        a.dropdown-toggle data-toggle="dropdown" href="#"
          = current_user.full_name
          b.caret
        ul.dropdown-menu role="menu"
          li
            = link_to "Settings", 
              '#'
          li
            = link_to 'Logout',
              destroy_user_session_path,
              method: :delete 
    - else
      li
        = link_to "Login",
          new_user_session_path
      li  
        = link_to "Sign Up",
          new_user_registration_path
  h3.text-muted 
    = link_to HipService, root_url

app/views/layout_components/_header_message.html.slim
- if content_for?(:page_header).present?
  .page-header
    h3 = yield(:page_header)

app/views/layouts/application.html.slim
doctype html
html
  head
    title= content_for?(:title) ? yield(:title) : 'HipService'
    = stylesheet_link_tag "application", media: "all"
    = csrf_meta_tags
    = javascript_include_tag 'application', media: 'all'
    = javascript_tag "$(function() { #{yield(:javascript_code)} });" if content_for? :javascript_code
    
  body
    .container
      = render 'layout_components/header'
      #notice
        = render 'layout_components/flash_messages'
      = render 'layout_components/header_message'
      = yield
      .footer
        p © HipService 2013

app/views/tasks/_create_form.html.slim
#task_form
	= form_tag tasks_url, remote: true, method: :post do
		.col-md-3
		  = hidden_field_tag "task[user_id]", current_user.id
		  = label_tag "Новая задача"
		  br
		  = text_area_tag 'task[description]',nil, class: 'pull-left date_range'
	    = label_tag 'Время окончания'
	    br
	    = text_field_tag 'task[end_date]', nil, id: 'datepicker'
		= submit_tag "Save", class: 'btn btn-primary save_task'

app/views/tasks/_task.html.slim
li.b-task{id='task_#{task.id}'}
	- if task.status == 'pending' && task.end_date > Time.now()
		= check_box_tag 'accept', task.id
	label.pull-righg.task_label
		- if task.status == 'done'
			s.disabled = "#{task.description}  -  задача выполнено #{task.updated_at.strftime('%d %B %Y')}"
		- elsif task.end_date < Time.now()
			.expired = "#{task.description}  -  задача не выполнена до #{task.end_date.strftime('%d %B %Y')}"
		- else
			= "#{task.description}  -  задача заканчивается #{task.end_date.strftime('%d %B %Y')}"

app/views/tasks/create.js.erb
<% if  @task.errors.blank? %>
	$('.tasks').prepend("<%= escape_javascript(render(
      'task', task: @task
    )) %>");
	$('textarea').val('');
	$('#datepicker').val('');
<% else %>
	$('#notice').html("<%= escape_javascript(render('layout_components/flash_messages')) %>");
	<% flash[:error] = nil %>
<% end %>

app/views/tasks/index.html.slim
.row.bottom20
	= render 'create_form'
.clearfix
.row
	.col-md-6
		ul#b-feeds__container.tasks
			= render tasks

= content_for(:javascript_code) do
  | DatePicker.init();
  | TaskStatus.change();

app/views/tasks/update.js.erb
<% if  task.errors.blank? %>
	$("#task_<%= task.id %>").replaceWith("<%= escape_javascript(render(
      'task', task: task
    )) %>");
<% end %>